version: '3'

services:
  zookeeper:
    image: zookeeper:latest
    ports:
    - "2181"

  customer-microservice:
    image: open-insights/customer-microservice:latest
    ports:
    - "8081"
    environment:
    - SPRING_CLOUD_ZOOKEEPER_CONNECT-STRING=zookeeper:2181
    depends_on:
    - zookeeper

  subscription-microservice:
    image: open-insights/subscription-microservice:latest
    ports:
    - "8083"
    environment:
    - SPRING_CLOUD_ZOOKEEPER_CONNECT-STRING=zookeeper:2181
    depends_on:
    - zookeeper

  subscription-management-microservice:
    image: open-insights/subscription-management-microservice:latest
    ports:
    - "8084"
    environment:
    - SPRING_CLOUD_ZOOKEEPER_CONNECT-STRING=zookeeper:2181
    depends_on:
    - zookeeper

  microservices-authentication-service:
    image: open-insights/microservices-authentication-service:latest
    ports:
    - "8080:8080"
    environment:
    - SPRING_CLOUD_ZOOKEEPER_CONNECT-STRING=zookeeper:2181
    depends_on:
    - zookeeper

    